#!/usr/bin/env bash

CLASSPATH=./lib/batik-1.8/batik-1.8.jar:\
./lib/batik-1.8/batik-rasterizer-1.8.jar:\
./lib/batik-1.8/batik-slideshow-1.8.jar:\
./lib/batik-1.8/batik-squiggle-1.8.jar:\
./lib/batik-1.8/batik-svgpp-1.8.jar:\
./lib/batik-1.8/batik-ttf2svg-1.8.jar:\
./lib/batik-1.8/extensions/batik-rasterizer-ext-1.8.jar:\
./lib/batik-1.8/extensions/batik-squiggle-ext-1.8.jar:\
./lib/batik-1.8/lib/batik-anim-1.8.jar:\
./lib/batik-1.8/lib/batik-awt-util-1.8.jar:\
./lib/batik-1.8/lib/batik-bridge-1.8.jar:\
./lib/batik-1.8/lib/batik-codec-1.8.jar:\
./lib/batik-1.8/lib/batik-css-1.8.jar:\
./lib/batik-1.8/lib/batik-dom-1.8.jar:\
./lib/batik-1.8/lib/batik-ext-1.8.jar:\
./lib/batik-1.8/lib/batik-extension-1.8.jar:\
./lib/batik-1.8/lib/batik-gui-util-1.8.jar:\
./lib/batik-1.8/lib/batik-gvt-1.8.jar:\
./lib/batik-1.8/lib/batik-parser-1.8.jar:\
./lib/batik-1.8/lib/batik-script-1.8.jar:\
./lib/batik-1.8/lib/batik-svg-dom-1.8.jar:\
./lib/batik-1.8/lib/batik-svggen-1.8.jar:\
./lib/batik-1.8/lib/batik-swing-1.8.jar:\
./lib/batik-1.8/lib/batik-transcoder-1.8.jar:\
./lib/batik-1.8/lib/batik-util-1.8.jar:\
./lib/batik-1.8/lib/batik-xml-1.8.jar:\
./lib/batik-1.8/lib/fop-transcoder-allinone-1.1.jar:\
./lib/batik-1.8/lib/js.jar:\
./lib/batik-1.8/lib/xalan-2.7.0.jar:\
./lib/batik-1.8/lib/xerces_2_5_0.jar:\
./lib/batik-1.8/lib/xml-apis-1.3.04.jar:\
./lib/batik-1.8/lib/xml-apis-ext-1.3.04.jar:\
./lib/batik-1.8/lib/xmlgraphics-commons-2.0.jar:\
./lib/poi-3.14-20160307.jar:\
./lib/poi-ooxml-3.14-20160307.jar:\
./lib/poi-ooxml-schemas-3.14-20160307.jar:\
./lib/resolver.jar:\
./lib/serializer.jar:\
./lib/xercesImpl.jar:\
./lib/xml-apis.jar:\
./lib/xmlbeans-2.6.0.jar

java -cp bin:$CLASSPATH SVGConverter


